---
deployment:
  tasks:
    # каталоги
    - export REPO=/home/v92793/repositories/cogintech-ai-landing
    - export PUBLIC=/home/v92793/public_html/landing
    # сборка
    - /usr/bin/env npm --prefix $REPO ci --silent       # или bun install
    - /usr/bin/env npm --prefix $REPO run build
    # выкладка 
    - /usr/bin/mkdir -p $PUBLIC
    - /usr/bin/rsync -az --delete $REPO/dist/ $PUBLIC/
    # настройка кеширования
    - echo 'Header set Cache-Control "max-age=31536000, public, immutable"' > $PUBLIC/.htaccess
    - echo 'Header set Expires "Thu, 31 Dec 2025 23:59:59 GMT"' >> $PUBLIC/.htaccess
    - echo '<FilesMatch "\.(mp4|gif|png|jpg|jpeg|svg|webp|ico|css|js|woff|woff2|ttf|eot)$">' >> $PUBLIC/.htaccess
    - echo '  Header set Cache-Control "max-age=31536000, public, immutable"' >> $PUBLIC/.htaccess
    - echo '</FilesMatch>' >> $PUBLIC/.htaccess


