---
deployment:
  tasks:
    - export DEPLOYPATH=/home/v92793/public_html/landing       # ← полный путь
    - cd $DEPLOYPATH && /bin/rm -rf *                        # очистить каталог
    - cd $DEPLOYDIR                                          # $DEPLOYDIR = путь репо
    - /opt/cpanel/ea-nodejs20/bin/npm ci --silent            # или bun install
    - /opt/cpanel/ea-nodejs20/bin/npm run build              # создаёт dist/
    - /usr/bin/rsync -az --delete dist/ $DEPLOYPATH/         # копируем билд

