
[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-prerender-spa"

[plugins.inputs]
  # Prerender all routes for better SEO
  routes = [
    "/",
    "/old-landing",
    "/about-us",
    "/our-team", 
    "/careers",
    "/news",
    "/contact",
    "/case-studies",
    "/technology",
    "/blog",
    "/privacy-policy",
    "/terms-of-service",
    "/cookie-policy"
  ]
  # Enable crawling for better discovery
  crawl = true
  # Set user agent for bot detection
  userAgent = "Googlebot"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/*.(png|jpg|jpeg|gif|svg|mp4|webm|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
